### ISSUE TITLE
Qwen1.5 seems not using NTK

### ISSUE THREAD

**Issue by PengWenChen** [TIGER-AI-Lab/LongICLBench#3]
Hi~ Thanks for sharing the evaluation code!
I would like to ask where did Qwen1.5 add ntk-interpolation?
I traced the code with Qwen2 with [huggingface transformers](https://huggingface.co/docs/transformers/model_doc/qwen2), and found they remove the ntk-interpolation (Qwen1 has ntk but Qwen2/1.5 don't have) 

Qwen1.5 should only use RoPE, right?

**Comment by wenhuchen** [comment]
@ltl3A87 can you check this?

**Comment by ltl3A87** [comment]
Hi, yes, thanks for rectifying it. In Qwen1.5 and 2, they remove ntk-interpolation, will update the table.
