### ISSUE TITLE
ConnectionError: Couldn't reach

### ISSUE THREAD

**Issue by Jianwei-Lv** [TIGER-AI-Lab/LongICLBench#4]
dataset = load_dataset("go_emotions")

some issues are occur:

ConnectionError: Couldn't reach https://huggingface.co/datasets/go_emotions/resolve/add492243ff905527e67aeb8b80c082af02207c3/README.md (ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))

What should I do ? thanks!

**Comment by wenhuchen** [comment]
It's the firewall issue in China. It's hard to solve from our side.

**Comment by Jianwei-Lv** [comment]
Thanks for your response!
I have solved this issues.

First, download "go_emotions" dataset from huggingface at your local path,
Second, dataset = load_dataset(your local path).

Success!!!
hahaha
